#!/usr/bin/env bash
# Guided secrets fill for Jarvis (interactive; no LLM; values never printed back).
# Writes live profile .env under the single remote data volume.
#
# Usage:
#   ./hermes/scripts/jarvis-secrets-wizard.sh
#   ./hermes/scripts/jarvis-secrets-wizard.sh --data-dir "$HOME/.jarvis/hermes-data"
#   ./hermes/scripts/jarvis-secrets-wizard.sh --check   # report which capabilities look set (no values)
#
# Capabilities (see docs/agents/runbooks/jarvis-capabilities.md):
#   model | email | slack
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERMES_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${HERMES_DIR}/jarvis-profile/.env.template"

DATA_DIR="${JARVIS_HERMES_DATA:-${HOME}/.jarvis/hermes-data}"
CHECK_ONLY=0

die() { echo "jarvis-secrets-wizard: error: $*" >&2; exit 1; }
info() { echo "jarvis-secrets-wizard: $*" >&2; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --data-dir) DATA_DIR="${2:-}"; shift 2 ;;
    --check) CHECK_ONLY=1; shift ;;
    -h|--help)
      sed -n '2,16p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) die "unknown option: $1" ;;
  esac
done

[[ -f "$TEMPLATE" ]] || die "missing template: $TEMPLATE"
[[ -d "$DATA_DIR" ]] || die "data dir missing: $DATA_DIR (run jarvis-bring-up.sh first)"

# Resolve live .env path (create profile dir if needed)
ENV_FILE=""
for cand in \
  "${DATA_DIR}/profiles/jarvis/.env" \
  "${DATA_DIR}/hermes/profiles/jarvis/.env"
do
  if [[ -f "$cand" ]]; then
    ENV_FILE="$cand"
    break
  fi
  if [[ -d "$(dirname "$cand")" ]]; then
    ENV_FILE="$cand"
    break
  fi
done
if [[ -z "$ENV_FILE" ]]; then
  ENV_FILE="${DATA_DIR}/profiles/jarvis/.env"
fi
mkdir -p "$(dirname "$ENV_FILE")"

# Load existing env file into associative-like vars without exporting to children unnecessarily
declare -A CUR=()
if [[ -f "$ENV_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      val="${val%\"}"
      val="${val#\"}"
      CUR["$key"]="$val"
    fi
  done < "$ENV_FILE"
fi

has() {
  local k="$1"
  [[ -n "${CUR[$k]:-}" ]]
}

mark() {
  local k="$1"
  if has "$k"; then echo "set"; else echo "missing"; fi
}

check_report() {
  echo "Live env file: $ENV_FILE"
  echo "  (values never printed)"
  echo ""
  echo "Model auth:"
  echo "  ANTHROPIC_API_KEY     $(mark ANTHROPIC_API_KEY)"
  echo "  OPENAI_API_KEY        $(mark OPENAI_API_KEY)"
  echo "  OPENROUTER_API_KEY    $(mark OPENROUTER_API_KEY)"
  echo "Email digest:"
  echo "  JARVIS_SMTP_HOST      $(mark JARVIS_SMTP_HOST)"
  echo "  JARVIS_SMTP_PORT      $(mark JARVIS_SMTP_PORT)"
  echo "  JARVIS_SMTP_USER      $(mark JARVIS_SMTP_USER)"
  echo "  JARVIS_SMTP_PASSWORD  $(mark JARVIS_SMTP_PASSWORD)"
  echo "  JARVIS_DIGEST_TO      $(mark JARVIS_DIGEST_TO)"
  echo "  JARVIS_DIGEST_FROM    $(mark JARVIS_DIGEST_FROM)"
  echo "Slack:"
  echo "  SLACK_BOT_TOKEN       $(mark SLACK_BOT_TOKEN)"
  echo "  SLACK_APP_TOKEN       $(mark SLACK_APP_TOKEN)"
  echo "  SLACK_ALLOWED_USERS   $(mark SLACK_ALLOWED_USERS)"
  echo "  SLACK_HOME_CHANNEL    $(mark SLACK_HOME_CHANNEL)"
}

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  check_report
  exit 0
fi

# Prompt helpers — read -s for secrets; never echo values back
ask_yn() {
  local prompt="$1" def="${2:-n}" ans
  read -r -p "$prompt [$def]: " ans || true
  ans="${ans:-$def}"
  case "$ans" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

ask_val() {
  # $1=var name  $2=prompt  $3=secret? (1/0)  $4=default optional
  local key="$1" prompt="$2" secret="${3:-0}" def="${4:-}"
  local cur="${CUR[$key]:-}" shown
  if [[ -n "$cur" ]]; then
    shown="(currently set — enter to keep)"
  elif [[ -n "$def" ]]; then
    shown="(default: $def)"
  else
    shown="(empty)"
  fi
  local input=""
  if [[ "$secret" -eq 1 ]]; then
    read -r -s -p "$prompt $shown: " input || true
    echo "" >&2
  else
    read -r -p "$prompt $shown: " input || true
  fi
  if [[ -z "$input" ]]; then
    if [[ -n "$cur" ]]; then
      return 0
    elif [[ -n "$def" ]]; then
      CUR["$key"]="$def"
      return 0
    else
      return 0
    fi
  fi
  CUR["$key"]="$input"
}

write_env() {
  local tmp
  tmp="$(mktemp)"
  {
    echo "# Jarvis live secrets — generated by jarvis-secrets-wizard.sh"
    echo "# Path: $ENV_FILE"
    echo "# DO NOT COMMIT. Values are local to the single remote volume only."
    echo ""
    echo "# --- Model ---"
    [[ -n "${CUR[ANTHROPIC_API_KEY]:-}" ]] && echo "ANTHROPIC_API_KEY=${CUR[ANTHROPIC_API_KEY]}"
    [[ -n "${CUR[OPENAI_API_KEY]:-}" ]] && echo "OPENAI_API_KEY=${CUR[OPENAI_API_KEY]}"
    [[ -n "${CUR[OPENROUTER_API_KEY]:-}" ]] && echo "OPENROUTER_API_KEY=${CUR[OPENROUTER_API_KEY]}"
    echo ""
    echo "# --- Email digest ---"
    [[ -n "${CUR[JARVIS_SMTP_HOST]:-}" ]] && echo "JARVIS_SMTP_HOST=${CUR[JARVIS_SMTP_HOST]}"
    [[ -n "${CUR[JARVIS_SMTP_PORT]:-}" ]] && echo "JARVIS_SMTP_PORT=${CUR[JARVIS_SMTP_PORT]}"
    [[ -n "${CUR[JARVIS_SMTP_USER]:-}" ]] && echo "JARVIS_SMTP_USER=${CUR[JARVIS_SMTP_USER]}"
    [[ -n "${CUR[JARVIS_SMTP_PASSWORD]:-}" ]] && echo "JARVIS_SMTP_PASSWORD=${CUR[JARVIS_SMTP_PASSWORD]}"
    [[ -n "${CUR[JARVIS_SMTP_STARTTLS]:-}" ]] && echo "JARVIS_SMTP_STARTTLS=${CUR[JARVIS_SMTP_STARTTLS]}"
    [[ -n "${CUR[JARVIS_DIGEST_TO]:-}" ]] && echo "JARVIS_DIGEST_TO=${CUR[JARVIS_DIGEST_TO]}"
    [[ -n "${CUR[JARVIS_DIGEST_FROM]:-}" ]] && echo "JARVIS_DIGEST_FROM=${CUR[JARVIS_DIGEST_FROM]}"
    echo ""
    echo "# --- Slack ---"
    [[ -n "${CUR[SLACK_BOT_TOKEN]:-}" ]] && echo "SLACK_BOT_TOKEN=${CUR[SLACK_BOT_TOKEN]}"
    [[ -n "${CUR[SLACK_APP_TOKEN]:-}" ]] && echo "SLACK_APP_TOKEN=${CUR[SLACK_APP_TOKEN]}"
    [[ -n "${CUR[SLACK_ALLOWED_USERS]:-}" ]] && echo "SLACK_ALLOWED_USERS=${CUR[SLACK_ALLOWED_USERS]}"
    [[ -n "${CUR[SLACK_ALLOWED_CHANNELS]:-}" ]] && echo "SLACK_ALLOWED_CHANNELS=${CUR[SLACK_ALLOWED_CHANNELS]}"
    [[ -n "${CUR[SLACK_HOME_CHANNEL]:-}" ]] && echo "SLACK_HOME_CHANNEL=${CUR[SLACK_HOME_CHANNEL]}"
  } > "$tmp"
  # Restrictive perms
  chmod 600 "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  info "wrote $ENV_FILE (mode 600; values not logged)"
}

info "Interactive secrets wizard for Jarvis"
info "Volume: $DATA_DIR"
info "Will write: $ENV_FILE"
info "Press enter to keep an existing value. Secrets are hidden as you type."
echo ""

check_report
echo ""

if ask_yn "Configure model API keys?" "y"; then
  ask_val ANTHROPIC_API_KEY "ANTHROPIC_API_KEY" 1
  ask_val OPENAI_API_KEY "OPENAI_API_KEY" 1
  ask_val OPENROUTER_API_KEY "OPENROUTER_API_KEY" 1
fi

if ask_yn "Configure email digest SMTP?" "y"; then
  ask_val JARVIS_SMTP_HOST "SMTP host" 0
  ask_val JARVIS_SMTP_PORT "SMTP port" 0 "587"
  ask_val JARVIS_SMTP_USER "SMTP user" 0
  ask_val JARVIS_SMTP_PASSWORD "SMTP password" 1
  ask_val JARVIS_SMTP_STARTTLS "STARTTLS 1/0" 0 "1"
  ask_val JARVIS_DIGEST_TO "Digest To address" 0
  ask_val JARVIS_DIGEST_FROM "Digest From address" 0
fi

if ask_yn "Configure Slack Socket Mode?" "y"; then
  ask_val SLACK_BOT_TOKEN "SLACK_BOT_TOKEN (xoxb-…)" 1
  ask_val SLACK_APP_TOKEN "SLACK_APP_TOKEN (xapp-…)" 1
  ask_val SLACK_ALLOWED_USERS "SLACK_ALLOWED_USERS (member ids)" 0
  ask_val SLACK_HOME_CHANNEL "SLACK_HOME_CHANNEL (optional C…)" 0
fi

echo ""
if ask_yn "Write live .env now?" "y"; then
  write_env
  echo ""
  check_report
  info "Restart container so Hermes reloads env if already running:"
  info "  docker compose -f hermes/docker/compose.jarvis.yaml restart"
else
  info "aborted — no write"
  exit 1
fi
